### ISSUE TITLE
Robertz Bugz: drawing zones/roads struggles to catch up if you try to do it too fast.

### ISSUE THREAD

**Issue by Rubbon** [Gerrudo/reticulating-splines#58]
I find that I have to hold my mouse on the same tile for about a second before being able to drag an area or release the button to place the tile; otherwise the placement area will either start on a later tile or, in the case of trying to place 1 tile, it won't place at all.

**Comment by Gerrudo** [comment]
To give some context, I believe this is due to the default slow tap/click player input options unity provides, hopefully adjusting these values will fix the issue as it does make it a little awkward when trying to draw out a road or zone:


![Image](https://github.com/user-attachments/assets/6bbce32f-af80-4b7d-a7ae-23a4dfe7f179)
